# Introduction to numpy:

## Package for scientific computing with Python


Numerical Python, or "Numpy" for short, is a foundational package on which many of the most common data science packages are built. Numpy provides us with high performance multi-dimensional arrays which we can use as vectors or matrices.

The key features of numpy are:

* ndarrays: n-dimensional arrays of the same data type which are fast and space-efficient. There are a number of built-in methods for ndarrays which allow for rapid processing of data without using loops (e.g., compute the mean).
*Broadcasting: a useful tool which defines implicit behavior between multi-dimensional arrays of different sizes.
*Vectorization: enables numeric operations on ndarrays.
*Input/Output: simplifies reading and writing of data from/to file.

_Additional Recommended Resources:_

Numpy Documentation

_Python for Data Analysis by Wes McKinney_

_Python Data science Handbook by Jake VanderPlas_

# Getting started with ndarray


ndarrays are time and space-efficient multidimensional arrays at the core of numpy. Like the data structures in Week 2, let's get started by creating ndarrays using the numpy package.



# How to create Rank 1 numpy arrays:



In [2]:
import numpy as np

an_array = np.array([3, 33, 333])  # Create a rank 1 array

print(type(an_array))              # The type of an ndarray is: "<class 'numpy.ndarray'>"


<class 'numpy.ndarray'>


In [3]:
an_array2 = np.array([[3, 33, 333],[4,44,444]])
an_array2.shape

(2, 3)

In [4]:
an_array2 = np.array([[3, 33, 333],[4,44,444]])
an_array2.shape

(2, 3)

In [5]:
# because this is a 1-rank array, we need only one index to accesss each element
print(an_array[0], an_array[1], an_array[2]) 

3 33 333


In [6]:
an_array[0] =888            # ndarrays are mutable, here we change an element of the array

print(an_array)

[888  33 333]


## How to create a Rank 2 numpy array:

A rank 2 ndarray is one with two dimensions. Notice the format below of [ [row] , [row] ]. 2 dimensional arrays are great for representing matrices which are often useful in data science.

In [7]:
another = np.array([[11,12,13],[21,22,23]])   # Create a rank 2 array

print(another)  # print the array

print("The shape is 2 rows, 3 columns: ", another.shape)  # rows x columns                   

print("Accessing elements [0,0], [0,1], and [1,0] of the ndarray: ", another[0, 0], ", ",another[0, 1],", ", another[1, 0])

[[11 12 13]
 [21 22 23]]
The shape is 2 rows, 3 columns:  (2, 3)
Accessing elements [0,0], [0,1], and [1,0] of the ndarray:  11 ,  12 ,  21


## There are many way to create numpy arrays:

Here we create a number of different size arrays with different shapes and different pre-filled values. numpy has a number of built in methods which help us quickly and easily create multidimensional arrays.

In [8]:
import numpy as np

# create a 2x2 array of zeros
ex1 = np.zeros((2,2))      
print(ex1)                              

[[0. 0.]
 [0. 0.]]


In [9]:
# create a 2x2 array filled with 9.0
ex2 = np.full((3,3), 9.0)  
print(ex2)   

[[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]


In [10]:
# create a 2x2 matrix with the diagonal 1s and the others 0
ex3 = np.eye(5,5)
print(ex3)  

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [11]:
# create an array of ones
ex4 = np.ones((2,2))
print(ex4)    

[[1. 1.]
 [1. 1.]]


In [12]:
# notice that the above ndarray (ex4) is actually rank 2, it is a 2x1 array
print(ex4.shape)

# which means we need to use two indexes to access an element
print()
print(ex4[0,0])

(2, 2)

1.0


In [13]:
# create an array of random floats between 0 and 1
ex5 = np.random.random((2,2))
print(ex5)    

[[0.31710176 0.24079526]
 [0.23705678 0.74706007]]


# Array Indexing


## Slice indexing:

Similar to the use of slice indexing with lists and strings, we can use slice indexing to pull out sub-regions of ndarrays.

In [14]:
import numpy as np

# Rank 2 array of shape (3, 4)
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


Use array slicing to get a subarray consisting of the first 2 rows x 2 columns.

In [15]:
a_slice = an_array[0:2, 1:3]
#select 0 and 1 rows, 1 and 2 column
print(a_slice)

[[12 13]
 [22 23]]


When you modify a slice, you actually modify the underlying array.



In [16]:
print("Before:", an_array[0, 1])   #inspect the element at 0, 1  
a_slice[0, 0] = 1000    # a_slice[0, 0] is the same piece of data as an_array[0, 1]
print("After:", an_array[0, 1])
print(an_array)

Before: 12
After: 1000
[[  11 1000   13   14]
 [  21   22   23   24]
 [  31   32   33   34]]


# Use both integer indexing & slice indexing



We can use combinations of integer indexing and slice indexing to create different shaped matrices.

In [17]:
# Create a Rank 2 array of shape (3, 4)
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [18]:
# Using both integer indexing & slicing generates an array of lower rank
row_rank1 = an_array[1, :]    # Rank 1 view 
print(row_rank1, row_rank1.shape)  # notice only a single []

[21 22 23 24] (4,)


In [19]:
# Slicing alone: generates an array of the same rank as the an_array
row_rank2 = an_array[1:2, :]  # Rank 2 view 
print(row_rank2, row_rank2.shape)   # Notice the [[ ]]

[[21 22 23 24]] (1, 4)


In [20]:
#We can do the same thing for columns of an array:

print()
col_rank1 = an_array[:, 1] 
col_rank2 = an_array[:, 1:2]

print(col_rank1, col_rank1.shape)  # Rank 1
print()
print(col_rank2, col_rank2.shape)  # Rank 2


[12 22 32] (3,)

[[12]
 [22]
 [32]] (3, 1)


# Array Indexing for changing elements:

Sometimes it's useful to use an array of indexes to access or change elements.

In [21]:
# Create a new array
an_array = np.array([[11,12,13], [21,22,23], [31,32,33], [41,42,43]])

print('Original Array:')
print(an_array)

Original Array:
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [22]:
# Create an array of indices
col_indices = np.array([0, 1, 2, 0])
print('\nCol indices picked : ', col_indices)

row_indices = np.arange(4) #arange will select 0, 1, 2, 3
print('\nRows indices picked : ', row_indices)


Col indices picked :  [0 1 2 0]

Rows indices picked :  [0 1 2 3]


In [23]:
# Examine the pairings of row_indices and col_indices.  These are the elements we'll change next.
for i,j in zip(row_indices,col_indices):
    print(i, ", ",j)
'''for i in row_indices:
    for j in col_indices:'''

0 ,  0
1 ,  1
2 ,  2
3 ,  0


'for i in row_indices:\n    for j in col_indices:'

In [24]:
# Select one element from each row
print('Values in the array at those indices: ',an_array[row_indices, col_indices])
#an_array[0, 0], an_array[1,1],an_array[2, 2], an_array[3,0] = an_array[row_indices, col_indices]

Values in the array at those indices:  [11 22 33 41]


In [25]:
# Change one element from each row using the indices selected
an_array[row_indices, col_indices] += 100000 #a = a + 10 is same  as a+=10

print('\nChanged Array:')
print(an_array)


Changed Array:
[[100011     12     13]
 [    21 100022     23]
 [    31     32 100033]
 [100041     42     43]]


# Boolean Indexing


## Array Indexing for changing elements:



In [26]:
# create a 3x2 array
an_array = np.array([[11,12], [21, 22], [31, 32]])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [27]:
# create a filter which will be boolean values for whether each element meets this condition
filter = (an_array > 15)
filter

array([[False, False],
       [ True,  True],
       [ True,  True]])

Notice that the filter is a same size ndarray as an_array which is filled with True for each element whose corresponding element in an_array which is greater than 15 and False for those elements whose value is less than 15.

In [28]:
# we can now select just those elements which meet that criteria
print(an_array[filter]) #values that are greater than 15.

[21 22 31 32]


In [29]:
# For short, we could have just used the approach below without the need for the separate filter array.

an_array[an_array > 15]

array([21, 22, 31, 32])

What is particularly useful is that we can actually change elements in the array applying a similar logical filter. Let's add 100 to all the even values.



In [30]:
an_array[an_array % 2 == 0] +=100 # a+=100 is same as a = a + 100
print(an_array)

[[ 11 112]
 [ 21 122]
 [ 31 132]]


# Datatypes and Array Operations


## Datatypes:

In [31]:
ex1 = np.array([11, 12]) # Python assigns the  data type
print(ex1.dtype)

int32


In [32]:
ex2 = np.array([11.0, 12.0]) # Python assigns the  data type
print(ex2.dtype)

float64


In [33]:
ex3 = np.array([11, 21], dtype=np.int64) #You can also tell Python the  data type
print(ex3.dtype)

int64


In [34]:
# you can use this to force floats into integers (using floor function)
ex4 = np.array([11.1,12.7], dtype=np.int64)
print(ex4.dtype)
print()
print(ex4)

int64

[11 12]


In [35]:
# you can use this to force integers into floats if you anticipate
# the values may change to floats later
ex5 = np.array([11, 21], dtype=np.float64)
print(ex5.dtype)
print()
print(ex5)


float64

[11. 21.]


#   Arithmetic Array Operations:



In [36]:
import numpy as np
x = np.array([[111,112],[121,122]], dtype=np.int)
y = np.array([[211.1,212.1],[221.1,222.1]], dtype=np.float64)

print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[211.1 212.1]
 [221.1 222.1]]


C:\Users\hp\AppData\Local\Temp/ipykernel_5768/2364180563.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.array([[111,112],[121,122]], dtype=np.int)


In [37]:
# add
print(x + y)         # The plus sign works
print()
print(np.add(x, y))  # so does the numpy function "add"

[[322.1 324.1]
 [342.1 344.1]]

[[322.1 324.1]
 [342.1 344.1]]


In [38]:
# multiply
print(x * y)
print()
print(np.multiply(x, y))

[[23432.1 23755.2]
 [26753.1 27096.2]]

[[23432.1 23755.2]
 [26753.1 27096.2]]


In [40]:
# subtract
print(x - y)
print()
print(np.subtract(x, y))


[[-100.1 -100.1]
 [-100.1 -100.1]]

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [41]:
# divide
print(x / y)
print()
print(np.divide(x, y))

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]


In [42]:
# square root
print(np.sqrt(x))

[[10.53565375 10.58300524]
 [11.         11.04536102]]


In [43]:
# exponent (e ** x)
print(np.exp(x))

[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


# Statistical Methods, Sorting, and

# Set Operations:

##  _Basic Statistical Operations:_



In [46]:
# setup a random 2 x 5 matrix
arr = 10 * np.random.randn(2,5) #random.random or random.randn or random.randint
print(arr)

[[ -8.60728835  19.15849448  -9.73770159   2.29593609  11.00619753]
 [ -2.60481428  14.88378581   3.1623642  -12.68913193   1.73815719]]


In [47]:
# compute the mean for all elements
print(arr.mean())

1.8605999132228583


In [48]:
# compute the means by row
print(arr.mean(axis = 1))

[2.82312763 0.8980722 ]


In [49]:
# compute the means by column
print(arr.mean(axis = 0))

[-5.60605132 17.02114014 -3.2876687  -5.19659792  6.37217736]


In [50]:
# sum all the elements
print(arr.sum())

18.605999132228582


In [51]:
# compute the medians
print(np.median(arr, axis = 1)) # by rows 1st and 2nd also

[2.29593609 1.73815719]


# sorting:

In [54]:
# create a 10 element array of randoms
unsorted = np.random.randn(10)

print(unsorted)

[ 1.71635213 -0.55074106 -0.25527539  1.63580224 -0.23768006 -0.23162791
  0.11375762 -1.61347    -0.4272855  -2.39168305]


In [55]:
# create copy and sort
sorted = np.array(unsorted)
sorted.sort() # it will arrange values in ascending order. i.e sorting

print(sorted)
print()
print(unsorted)

[-2.39168305 -1.61347    -0.55074106 -0.4272855  -0.25527539 -0.23768006
 -0.23162791  0.11375762  1.63580224  1.71635213]

[ 1.71635213 -0.55074106 -0.25527539  1.63580224 -0.23768006 -0.23162791
  0.11375762 -1.61347    -0.4272855  -2.39168305]


In [56]:
# inplace sorting
unsorted.sort() 
print(unsorted)

[-2.39168305 -1.61347    -0.55074106 -0.4272855  -0.25527539 -0.23768006
 -0.23162791  0.11375762  1.63580224  1.71635213]


## Finding Unique elements:



In [57]:
import numpy as np
array = np.array([1,2,1,4,2,1,4,2])
#print(array.unique())
print(np.unique(array)) # it will return unquie values

[1 2 4]


## Set Operations with np.array data type:



In [58]:
s1 = np.array(['desk','chair','bulb'])
s2 = np.array(['lamp','bulb','chair'])
print(s1, s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [59]:
print( np.intersect1d(s1, s2) )  #common values between s1 and s2

['bulb' 'chair']


In [60]:
print( np.union1d(s1, s2) ) #common and uncommon values between s1 and s2

['bulb' 'chair' 'desk' 'lamp']


In [61]:
print( np.setdiff1d(s1, s2) )# elements in s1 that are not in s2

['desk']


In [62]:
print( np.in1d(s1, s2) )#which element of s1 is also in s2

[False  True  True]




# Broadcasting:



Introduction to broadcasting.

For more details, please see:
https://docs.scipy.org/doc/numpy-1.10.1/user/basics.broadcasting.html

In [63]:
import numpy as np

start = np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [64]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2])
print(add_rows)

[1 0 2]


In [65]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [66]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]]) # print(add_cols) 
print(add_cols)
add_cols = add_cols.T #transpose: coverts rows into columns and vice versa

print(add_cols)

[[0 1 2 3]]
[[0]
 [1]
 [2]
 [3]]


In [67]:
# add to each column of 'start' using broadcasting
y = start + add_cols 
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [68]:
# this will just broadcast in both dimensions
add_scalar = np.array([1])  
print(start+add_scalar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Example from the slides:



In [69]:
# create our 3x4 matrix
arrA = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arrA)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [70]:
# create our 4x1 array
arrB = [0,1,0,2]
print(arrB)

[0, 1, 0, 2]


In [71]:
# add the two together using broadcasting
print(arrA + arrB)

[[ 1  3  3  6]
 [ 5  7  7 10]
 [ 9 11 11 14]]


## Binary Format:



In [72]:
import numpy as np
x = np.array([ 23.23, 24.24] )

In [73]:
np.save('an_array', x) #saves the values in x to an_array
np.load('an_array.npy') 

array([23.23, 24.24])

## Text Format:



In [74]:
np.savetxt('array.txt', X=x, delimiter=',')


In [75]:
## For Windows replace "cat" with "type"
!cat array.txt

'cat' is not recognized as an internal or external command,
operable program or batch file.


In [76]:
np.savetxt('array.txt', X=x, delimiter=',') #savetxt function will store your file in text format.
np.loadtxt('array.txt', delimiter=',') #delimiter and sep are same which is seperated by comma.


array([23.23, 24.24])



# Additional Common ndarray Operations



## Dot Product on Matrices and Inner Product on Vectors:



In [77]:
# determine the dot product of two matrices
x2d = np.array([[1,1],[1,1]])
y2d = np.array([[2,2],[2,2]]) 
print(x2d)
print()
print(y2d)
print()
print(x2d.dot(y2d))
print()
print(np.dot(x2d, y2d))

[[1 1]
 [1 1]]

[[2 2]
 [2 2]]

[[4 4]
 [4 4]]

[[4 4]
 [4 4]]


In [78]:
# determine the inner product of two vectors
a1d = np.array([9 , 9 ])
b1d = np.array([10, 10])

print(a1d.dot(b1d))
print()
print(np.dot(a1d, b1d))

180

180


# Sum:



In [79]:
# sum elements in the array
ex1 = np.array([[11,12],[21,22]])

print(np.sum(ex1))          # add all members

66


In [80]:
print(np.sum(ex1, axis=0))  # columnwise sum

[32 34]


In [81]:
print(np.sum(ex1, axis=1))  # rowwise sum


[23 43]


# Element-wise Functions:


For example, let's compare two arrays values to get the maximum of each.





In [82]:
# random array
x = np.random.randn(8)
x


array([-2.40045685, -0.00789468,  0.81748075,  2.51154257,  1.29292722,
        1.17345338,  0.09142861, -0.97149411])

In [83]:
# another random array
y = np.random.randn(8)
y

array([-0.09545852,  0.54487252, -1.08807284,  0.43521389,  0.06148463,
        0.24147332,  0.10484639, -0.64506604])

In [84]:
# returns element wise maximum between two arrays
import numpy as np
x = np.random.randn(2,3)
y = np.random.randn(2,3)
np.maximum(x, y)

array([[ 0.67435561, -0.19240754, -0.01949939],
       [ 0.37026791,  0.83927434,  2.17508135]])

# Reshaping array:



In [85]:
# grab values from 0 through 19 in an array
arr = np.arange(20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [86]:
# reshape to be a 4 x 5 matrix
arr.reshape(4,5) #5, 4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# Transpose:

In [87]:
# transpose
ex1 = np.array([[11,12],[21,22]])

ex1.T

array([[11, 21],
       [12, 22]])

# Indexing using where():



In [88]:
x_1 = np.array([1,2,3,4,5])

y_1 = np.array([11,22,33,44,55])
# where we have true in filter it will print x_1 value and for false y_1 value
# this is the working of .where function
filter = np.array([True, False, True, False, True])

In [89]:
out = np.where(filter, x_1, y_1)
print(out)

[ 1 22  3 44  5]


In [90]:
mat = np.random.rand(5,5)
mat

array([[0.5122697 , 0.06854843, 0.46484933, 0.19636438, 0.42714816],
       [0.17724115, 0.88965326, 0.10868686, 0.47907449, 0.24571789],
       [0.69978501, 0.8376376 , 0.4005091 , 0.51275208, 0.61035147],
       [0.72187293, 0.24275177, 0.5964124 , 0.05458396, 0.4579481 ],
       [0.66869329, 0.48926694, 0.76823026, 0.82223447, 0.08127425]])

In [91]:
np.where( mat > 0.5, 1000, -1)


array([[1000,   -1,   -1,   -1,   -1],
       [  -1, 1000,   -1,   -1,   -1],
       [1000, 1000,   -1, 1000, 1000],
       [1000,   -1, 1000,   -1,   -1],
       [1000,   -1, 1000, 1000,   -1]])

In [93]:
'''
if mat > 0.5:
    replace(1000)
else:
    replace(-1)'''

'\nif mat > 0.5:\n    replace(1000)\nelse:\n    replace(-1)'

# "any" or "all" conditionals:

In [94]:
arr_bools = np.array([ True, False, True, True, False ])

In [95]:
arr_bools.any() #is any value True

True

In [96]:
arr_bools.all() # are all values True

False

# Random Number Generation:



In [97]:
import numpy as np
Y = np.random.normal(size = (1,5))
print(Y)

[[ 0.17018201  0.39647311 -0.32008972  1.12805638  0.94018074]]


In [98]:
Z = np.random.randint(low=2,high=50,size=4) #int integer values
print(Z) # low for lower limits and high for higher limits

[ 5  8 27  4]


In [99]:
np.random.permutation(Z) #return a new ordering of elements in Z

array([ 4, 27,  8,  5])

In [100]:
np.random.uniform(size=4) #uniform distribution

array([0.36375923, 0.28656307, 0.24499346, 0.59137377])

In [101]:
np.random.normal(size=4) #normal distributionsize=4

array([ 1.79750041, -0.9756044 ,  0.19062439, -0.82563167])

# Merging data sets:

In [102]:
K = np.random.randint(low=2,high=50,size=(2,2))
print(K)

print()
M = np.random.randint(low=2,high=50,size=(2,2))
print(M)

[[25 39]
 [43 35]]

[[39 25]
 [ 9 22]]


In [103]:
np.vstack((K,M)) # join vertically

array([[25, 39],
       [43, 35],
       [39, 25],
       [ 9, 22]])

In [104]:
np.hstack((K,M)) # join horizontally

array([[25, 39, 39, 25],
       [43, 35,  9, 22]])

In [105]:
np.concatenate([K, M], axis = 0)

array([[25, 39],
       [43, 35],
       [39, 25],
       [ 9, 22]])

In [106]:
np.concatenate([K, M.T], axis = 1)

array([[25, 39, 39,  9],
       [43, 35, 25, 22]])

In [107]:
np.concatenate([K, M], axis = 1)

array([[25, 39, 39, 25],
       [43, 35,  9, 22]])